FROM golang:1.11 as builder

ADD . /go/src/github.com/dnovikoff/mahjong-api
WORKDIR /go/src/github.com/dnovikoff/mahjong-api

RUN CGO_ENABLED=0 make gobin/example-client

FROM scratch
COPY --from=builder /go/src/github.com/dnovikoff/mahjong-api/gobin/example-client /usr/bin/example-client

CMD ["/usr/bin/example-client", "--config=/config.yaml"]
