FROM golang:1.11 as builder

ADD . /build
WORKDIR /build

RUN CGO_ENABLED=0 GOPROXY=off make gobin/example-client

FROM scratch
COPY --from=builder /build/gobin/example-client /usr/bin/example-client

CMD ["/usr/bin/example-client", "--config=/config.yaml"]
