// Code generated by protoc-gen-go. DO NOT EDIT.
// source: private/log/debug.proto

package log

import (
	fmt "fmt"
	game "github.com/dnovikoff/mahjong-api/genproto/private/game"
	game1 "github.com/dnovikoff/mahjong-api/genproto/public/game"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageSource int32

const (
	MessageSource_SOURCE_TYPE_UNSPECIFIED MessageSource = 0
	// Message produced by robot, replacing the offline player.
	MessageSource_SOURCE_ROBOT MessageSource = 1
	// Message resulted by settings on server side. Ex. AutoWin
	MessageSource_SOURCE_SETTINGS MessageSource = 2
	// Message produced by players action.
	MessageSource_SOURCE_CLIENT MessageSource = 3
	// Message produced by timeout on server side.
	MessageSource_SOURCE_TIMEOUT MessageSource = 4
)

var MessageSource_name = map[int32]string{
	0: "SOURCE_TYPE_UNSPECIFIED",
	1: "SOURCE_ROBOT",
	2: "SOURCE_SETTINGS",
	3: "SOURCE_CLIENT",
	4: "SOURCE_TIMEOUT",
}

var MessageSource_value = map[string]int32{
	"SOURCE_TYPE_UNSPECIFIED": 0,
	"SOURCE_ROBOT":            1,
	"SOURCE_SETTINGS":         2,
	"SOURCE_CLIENT":           3,
	"SOURCE_TIMEOUT":          4,
}

func (x MessageSource) String() string {
	return proto.EnumName(MessageSource_name, int32(x))
}

func (MessageSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c31fc8bf6262b98, []int{0}
}

// Format for storing logs. (Private usage)
type DebugLog struct {
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Storing information of created request
	Create *game.CreateRequest `protobuf:"bytes,2,opt,name=create,proto3" json:"create,omitempty"`
	// Debug information for investigations
	PlayerMessages       []*DebugMessages `protobuf:"bytes,3,rep,name=player_messages,json=playerMessages,proto3" json:"player_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DebugLog) Reset()         { *m = DebugLog{} }
func (m *DebugLog) String() string { return proto.CompactTextString(m) }
func (*DebugLog) ProtoMessage()    {}
func (*DebugLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31fc8bf6262b98, []int{0}
}

func (m *DebugLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugLog.Unmarshal(m, b)
}
func (m *DebugLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugLog.Marshal(b, m, deterministic)
}
func (m *DebugLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugLog.Merge(m, src)
}
func (m *DebugLog) XXX_Size() int {
	return xxx_messageInfo_DebugLog.Size(m)
}
func (m *DebugLog) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugLog.DiscardUnknown(m)
}

var xxx_messageInfo_DebugLog proto.InternalMessageInfo

func (m *DebugLog) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DebugLog) GetCreate() *game.CreateRequest {
	if m != nil {
		return m.Create
	}
	return nil
}

func (m *DebugLog) GetPlayerMessages() []*DebugMessages {
	if m != nil {
		return m.PlayerMessages
	}
	return nil
}

type DebugMessages struct {
	Messages             []*DebugMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DebugMessages) Reset()         { *m = DebugMessages{} }
func (m *DebugMessages) String() string { return proto.CompactTextString(m) }
func (*DebugMessages) ProtoMessage()    {}
func (*DebugMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31fc8bf6262b98, []int{1}
}

func (m *DebugMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugMessages.Unmarshal(m, b)
}
func (m *DebugMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugMessages.Marshal(b, m, deterministic)
}
func (m *DebugMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugMessages.Merge(m, src)
}
func (m *DebugMessages) XXX_Size() int {
	return xxx_messageInfo_DebugMessages.Size(m)
}
func (m *DebugMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugMessages.DiscardUnknown(m)
}

var xxx_messageInfo_DebugMessages proto.InternalMessageInfo

func (m *DebugMessages) GetMessages() []*DebugMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

type DebugMessage struct {
	Time *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	// Types that are valid to be assigned to OneofEvents:
	//	*DebugMessage_Client
	//	*DebugMessage_Server
	OneofEvents          isDebugMessage_OneofEvents `protobuf_oneof:"oneof_events"`
	Source               MessageSource              `protobuf:"varint,4,opt,name=source,proto3,enum=mahjong.private.log.MessageSource" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DebugMessage) Reset()         { *m = DebugMessage{} }
func (m *DebugMessage) String() string { return proto.CompactTextString(m) }
func (*DebugMessage) ProtoMessage()    {}
func (*DebugMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c31fc8bf6262b98, []int{2}
}

func (m *DebugMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugMessage.Unmarshal(m, b)
}
func (m *DebugMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugMessage.Marshal(b, m, deterministic)
}
func (m *DebugMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugMessage.Merge(m, src)
}
func (m *DebugMessage) XXX_Size() int {
	return xxx_messageInfo_DebugMessage.Size(m)
}
func (m *DebugMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DebugMessage proto.InternalMessageInfo

func (m *DebugMessage) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type isDebugMessage_OneofEvents interface {
	isDebugMessage_OneofEvents()
}

type DebugMessage_Client struct {
	Client *game1.Client `protobuf:"bytes,2,opt,name=client,proto3,oneof"`
}

type DebugMessage_Server struct {
	Server *game1.Server `protobuf:"bytes,3,opt,name=server,proto3,oneof"`
}

func (*DebugMessage_Client) isDebugMessage_OneofEvents() {}

func (*DebugMessage_Server) isDebugMessage_OneofEvents() {}

func (m *DebugMessage) GetOneofEvents() isDebugMessage_OneofEvents {
	if m != nil {
		return m.OneofEvents
	}
	return nil
}

func (m *DebugMessage) GetClient() *game1.Client {
	if x, ok := m.GetOneofEvents().(*DebugMessage_Client); ok {
		return x.Client
	}
	return nil
}

func (m *DebugMessage) GetServer() *game1.Server {
	if x, ok := m.GetOneofEvents().(*DebugMessage_Server); ok {
		return x.Server
	}
	return nil
}

func (m *DebugMessage) GetSource() MessageSource {
	if m != nil {
		return m.Source
	}
	return MessageSource_SOURCE_TYPE_UNSPECIFIED
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DebugMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DebugMessage_Client)(nil),
		(*DebugMessage_Server)(nil),
	}
}

func init() {
	proto.RegisterEnum("mahjong.private.log.MessageSource", MessageSource_name, MessageSource_value)
	proto.RegisterType((*DebugLog)(nil), "mahjong.private.log.DebugLog")
	proto.RegisterType((*DebugMessages)(nil), "mahjong.private.log.DebugMessages")
	proto.RegisterType((*DebugMessage)(nil), "mahjong.private.log.DebugMessage")
}

func init() { proto.RegisterFile("private/log/debug.proto", fileDescriptor_8c31fc8bf6262b98) }

var fileDescriptor_8c31fc8bf6262b98 = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xd1, 0x6e, 0xd3, 0x30,
	0x18, 0x85, 0x97, 0x75, 0xaa, 0xc6, 0xbf, 0xb6, 0x0b, 0x1e, 0xd2, 0xa2, 0x72, 0xb1, 0x52, 0x6e,
	0x2a, 0x24, 0x1c, 0x69, 0x08, 0x21, 0x40, 0x5c, 0xd0, 0x2e, 0x40, 0xc5, 0xd6, 0x4e, 0x49, 0x7a,
	0x01, 0x37, 0x51, 0x9a, 0xfe, 0xf5, 0x02, 0x49, 0x1c, 0x12, 0xa7, 0x12, 0xbc, 0x24, 0xef, 0xc1,
	0x53, 0xa0, 0xd8, 0x4e, 0xb5, 0xa1, 0x22, 0xb8, 0x89, 0x64, 0x9f, 0xef, 0xfc, 0x3e, 0x3e, 0x56,
	0xe0, 0x34, 0x2f, 0xe2, 0x4d, 0x28, 0xd0, 0x4e, 0x38, 0xb3, 0x57, 0xb8, 0xac, 0x18, 0xcd, 0x0b,
	0x2e, 0x38, 0x39, 0x49, 0xc3, 0x9b, 0x2f, 0x3c, 0xab, 0x97, 0x12, 0xa0, 0x09, 0x67, 0xfd, 0x33,
	0xc6, 0x39, 0x4b, 0xd0, 0x96, 0xc8, 0xb2, 0x5a, 0xdb, 0x22, 0x4e, 0xb1, 0x14, 0x61, 0x9a, 0x2b,
	0x57, 0xff, 0xac, 0x19, 0xc7, 0xc2, 0x54, 0x7d, 0x82, 0x12, 0x8b, 0x4d, 0x1c, 0xa1, 0x06, 0xac,
	0xbc, 0x5a, 0x26, 0x71, 0xa4, 0xf4, 0x28, 0x89, 0x31, 0x13, 0xbb, 0x94, 0xda, 0x84, 0x85, 0x52,
	0x86, 0x3f, 0x0d, 0x38, 0xbc, 0xa8, 0xa3, 0x5d, 0x72, 0x46, 0x5e, 0x02, 0x44, 0x05, 0x86, 0x02,
	0x57, 0x41, 0x28, 0x2c, 0x63, 0x60, 0x8c, 0x8e, 0xce, 0xfb, 0x54, 0xe5, 0xa2, 0x4d, 0x2e, 0xea,
	0x37, 0xb9, 0xdc, 0x7b, 0x9a, 0x7e, 0x2b, 0xc8, 0x6b, 0x68, 0xab, 0x85, 0xb5, 0x2f, 0x6d, 0x8f,
	0xe9, 0x9f, 0x77, 0xac, 0xcf, 0xa6, 0x13, 0xc9, 0xb8, 0xf8, 0xad, 0xc2, 0x52, 0xb8, 0xda, 0x42,
	0x3e, 0xc2, 0x71, 0x9e, 0x84, 0xdf, 0xb1, 0x08, 0x52, 0x2c, 0xcb, 0x90, 0x61, 0x69, 0xb5, 0x06,
	0xad, 0xd1, 0xd1, 0xf9, 0x90, 0xee, 0x68, 0x8a, 0xca, 0xbc, 0x57, 0x9a, 0x74, 0x7b, 0xca, 0xda,
	0xac, 0x87, 0x33, 0xe8, 0xde, 0x01, 0xc8, 0x1b, 0x38, 0xdc, 0x8e, 0x35, 0xe4, 0xd8, 0x47, 0xff,
	0x1c, 0xeb, 0x6e, 0x2d, 0xc3, 0x5f, 0x06, 0x74, 0x6e, 0x4b, 0x84, 0xc2, 0x41, 0xfd, 0x34, 0xff,
	0xd1, 0x8f, 0xe4, 0x08, 0x85, 0xb6, 0x7a, 0x0c, 0x5d, 0xcd, 0x83, 0xed, 0xe9, 0xaa, 0x12, 0xa9,
	0x7d, 0xd8, 0x73, 0x35, 0x55, 0xf3, 0xea, 0x89, 0xac, 0xd6, 0x2e, 0xde, 0x93, 0x5a, 0xcd, 0x2b,
	0x8a, 0xbc, 0x82, 0x76, 0xc9, 0xab, 0x22, 0x42, 0xeb, 0x60, 0x60, 0x8c, 0x7a, 0x7f, 0x29, 0x4d,
	0xa7, 0xf7, 0x24, 0xe9, 0x6a, 0xc7, 0xb8, 0x07, 0x1d, 0x9e, 0x21, 0x5f, 0x07, 0xb8, 0xc1, 0x4c,
	0x94, 0x4f, 0x7e, 0x40, 0xf7, 0x0e, 0x48, 0x1e, 0xc2, 0xa9, 0x37, 0x5f, 0xb8, 0x13, 0x27, 0xf0,
	0x3f, 0x5d, 0x3b, 0xc1, 0x62, 0xe6, 0x5d, 0x3b, 0x93, 0xe9, 0xbb, 0xa9, 0x73, 0x61, 0xee, 0x11,
	0x13, 0x3a, 0x5a, 0x74, 0xe7, 0xe3, 0xb9, 0x6f, 0x1a, 0xe4, 0x04, 0x8e, 0xf5, 0x8e, 0xe7, 0xf8,
	0xfe, 0x74, 0xf6, 0xde, 0x33, 0xf7, 0xc9, 0x7d, 0xe8, 0xea, 0xcd, 0xc9, 0xe5, 0xd4, 0x99, 0xf9,
	0x66, 0x8b, 0x10, 0xe8, 0x35, 0x63, 0xa7, 0x57, 0xce, 0x7c, 0xe1, 0x9b, 0x07, 0xe3, 0x17, 0x9f,
	0x9f, 0xb3, 0x58, 0xdc, 0x54, 0x4b, 0x1a, 0xf1, 0xd4, 0x5e, 0x65, 0x7c, 0x13, 0x7f, 0xe5, 0xeb,
	0xb5, 0xad, 0x6f, 0xf3, 0x34, 0xcc, 0x63, 0x9b, 0x61, 0x26, 0x7b, 0xb6, 0x6f, 0xfd, 0x5a, 0xcb,
	0xb6, 0xdc, 0x7a, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x38, 0x50, 0x45, 0xf1, 0x70, 0x03, 0x00,
	0x00,
}
