// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: private/log/log_service.proto

package log

import (
	context "context"
	log "github.com/dnovikoff/mahjong-api/genproto/public/log"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDebugLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogId string `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
}

func (x *GetDebugLogRequest) Reset() {
	*x = GetDebugLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_log_log_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDebugLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugLogRequest) ProtoMessage() {}

func (x *GetDebugLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_private_log_log_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebugLogRequest.ProtoReflect.Descriptor instead.
func (*GetDebugLogRequest) Descriptor() ([]byte, []int) {
	return file_private_log_log_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetDebugLogRequest) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

type GetDebugLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Debug *DebugLog `protobuf:"bytes,1,opt,name=debug,proto3" json:"debug,omitempty"`
}

func (x *GetDebugLogResponse) Reset() {
	*x = GetDebugLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_log_log_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDebugLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebugLogResponse) ProtoMessage() {}

func (x *GetDebugLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_private_log_log_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebugLogResponse.ProtoReflect.Descriptor instead.
func (*GetDebugLogResponse) Descriptor() ([]byte, []int) {
	return file_private_log_log_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetDebugLogResponse) GetDebug() *DebugLog {
	if x != nil {
		return x.Debug
	}
	return nil
}

type SaveLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log   *log.Log  `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	Debug *DebugLog `protobuf:"bytes,2,opt,name=debug,proto3" json:"debug,omitempty"`
}

func (x *SaveLogRequest) Reset() {
	*x = SaveLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_log_log_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLogRequest) ProtoMessage() {}

func (x *SaveLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_private_log_log_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLogRequest.ProtoReflect.Descriptor instead.
func (*SaveLogRequest) Descriptor() ([]byte, []int) {
	return file_private_log_log_service_proto_rawDescGZIP(), []int{2}
}

func (x *SaveLogRequest) GetLog() *log.Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *SaveLogRequest) GetDebug() *DebugLog {
	if x != nil {
		return x.Debug
	}
	return nil
}

type SaveLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveLogResponse) Reset() {
	*x = SaveLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_log_log_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLogResponse) ProtoMessage() {}

func (x *SaveLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_private_log_log_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLogResponse.ProtoReflect.Descriptor instead.
func (*SaveLogResponse) Descriptor() ([]byte, []int) {
	return file_private_log_log_service_proto_rawDescGZIP(), []int{3}
}

var File_private_log_log_service_proto protoreflect.FileDescriptor

var file_private_log_log_service_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x6c, 0x6f, 0x67, 0x2f, 0x6c, 0x6f,
	0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x13, 0x6d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x6c, 0x6f, 0x67, 0x1a, 0x17, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x6c, 0x6f,
	0x67, 0x2f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x6c, 0x6f, 0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4c,
	0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64,
	0x22, 0x4a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x65, 0x62,
	0x75, 0x67, 0x4c, 0x6f, 0x67, 0x52, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x22, 0x69, 0x0a, 0x0e,
	0x53, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x61,
	0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x03, 0x6c,
	0x6f, 0x67, 0x12, 0x33, 0x0a, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4c, 0x6f, 0x67,
	0x52, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x61, 0x76, 0x65, 0x4c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc4, 0x01, 0x0a, 0x0a, 0x4c,
	0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x62, 0x75, 0x67, 0x4c, 0x6f, 0x67, 0x12, 0x27, 0x2e, 0x6d, 0x61, 0x68, 0x6a, 0x6f,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x6d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x62, 0x75, 0x67,
	0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x07, 0x53,
	0x61, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x23, 0x2e, 0x6d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x6c, 0x6f, 0x67, 0x2e, 0x53, 0x61, 0x76,
	0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6d, 0x61,
	0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x6c, 0x6f,
	0x67, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x6e, 0x6f, 0x76, 0x69, 0x6b, 0x6f, 0x66, 0x66, 0x2f, 0x6d, 0x61, 0x68, 0x6a, 0x6f, 0x6e,
	0x67, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x6c, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_private_log_log_service_proto_rawDescOnce sync.Once
	file_private_log_log_service_proto_rawDescData = file_private_log_log_service_proto_rawDesc
)

func file_private_log_log_service_proto_rawDescGZIP() []byte {
	file_private_log_log_service_proto_rawDescOnce.Do(func() {
		file_private_log_log_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_private_log_log_service_proto_rawDescData)
	})
	return file_private_log_log_service_proto_rawDescData
}

var file_private_log_log_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_private_log_log_service_proto_goTypes = []interface{}{
	(*GetDebugLogRequest)(nil),  // 0: mahjong.private.log.GetDebugLogRequest
	(*GetDebugLogResponse)(nil), // 1: mahjong.private.log.GetDebugLogResponse
	(*SaveLogRequest)(nil),      // 2: mahjong.private.log.SaveLogRequest
	(*SaveLogResponse)(nil),     // 3: mahjong.private.log.SaveLogResponse
	(*DebugLog)(nil),            // 4: mahjong.private.log.DebugLog
	(*log.Log)(nil),             // 5: mahjong.log.Log
}
var file_private_log_log_service_proto_depIdxs = []int32{
	4, // 0: mahjong.private.log.GetDebugLogResponse.debug:type_name -> mahjong.private.log.DebugLog
	5, // 1: mahjong.private.log.SaveLogRequest.log:type_name -> mahjong.log.Log
	4, // 2: mahjong.private.log.SaveLogRequest.debug:type_name -> mahjong.private.log.DebugLog
	0, // 3: mahjong.private.log.LogService.GetDebugLog:input_type -> mahjong.private.log.GetDebugLogRequest
	2, // 4: mahjong.private.log.LogService.SaveLog:input_type -> mahjong.private.log.SaveLogRequest
	1, // 5: mahjong.private.log.LogService.GetDebugLog:output_type -> mahjong.private.log.GetDebugLogResponse
	3, // 6: mahjong.private.log.LogService.SaveLog:output_type -> mahjong.private.log.SaveLogResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_private_log_log_service_proto_init() }
func file_private_log_log_service_proto_init() {
	if File_private_log_log_service_proto != nil {
		return
	}
	file_private_log_debug_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_private_log_log_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDebugLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_log_log_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDebugLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_log_log_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_log_log_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_private_log_log_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_private_log_log_service_proto_goTypes,
		DependencyIndexes: file_private_log_log_service_proto_depIdxs,
		MessageInfos:      file_private_log_log_service_proto_msgTypes,
	}.Build()
	File_private_log_log_service_proto = out.File
	file_private_log_log_service_proto_rawDesc = nil
	file_private_log_log_service_proto_goTypes = nil
	file_private_log_log_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogServiceClient interface {
	GetDebugLog(ctx context.Context, in *GetDebugLogRequest, opts ...grpc.CallOption) (*GetDebugLogResponse, error)
	SaveLog(ctx context.Context, in *SaveLogRequest, opts ...grpc.CallOption) (*SaveLogResponse, error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) GetDebugLog(ctx context.Context, in *GetDebugLogRequest, opts ...grpc.CallOption) (*GetDebugLogResponse, error) {
	out := new(GetDebugLogResponse)
	err := c.cc.Invoke(ctx, "/mahjong.private.log.LogService/GetDebugLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) SaveLog(ctx context.Context, in *SaveLogRequest, opts ...grpc.CallOption) (*SaveLogResponse, error) {
	out := new(SaveLogResponse)
	err := c.cc.Invoke(ctx, "/mahjong.private.log.LogService/SaveLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServiceServer is the server API for LogService service.
type LogServiceServer interface {
	GetDebugLog(context.Context, *GetDebugLogRequest) (*GetDebugLogResponse, error)
	SaveLog(context.Context, *SaveLogRequest) (*SaveLogResponse, error)
}

// UnimplementedLogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLogServiceServer struct {
}

func (*UnimplementedLogServiceServer) GetDebugLog(context.Context, *GetDebugLogRequest) (*GetDebugLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDebugLog not implemented")
}
func (*UnimplementedLogServiceServer) SaveLog(context.Context, *SaveLogRequest) (*SaveLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveLog not implemented")
}

func RegisterLogServiceServer(s *grpc.Server, srv LogServiceServer) {
	s.RegisterService(&_LogService_serviceDesc, srv)
}

func _LogService_GetDebugLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDebugLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetDebugLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mahjong.private.log.LogService/GetDebugLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetDebugLog(ctx, req.(*GetDebugLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_SaveLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).SaveLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mahjong.private.log.LogService/SaveLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).SaveLog(ctx, req.(*SaveLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mahjong.private.log.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDebugLog",
			Handler:    _LogService_GetDebugLog_Handler,
		},
		{
			MethodName: "SaveLog",
			Handler:    _LogService_SaveLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "private/log/log_service.proto",
}
