// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log/log.proto

package log

import (
	fmt "fmt"
	base "github.com/dnovikoff/mahjong-api/genproto/base"
	rules "github.com/dnovikoff/mahjong-api/genproto/rules"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// All game reasons applied if only specified by rules.
type GameEndReason int32

const (
	GameEndReason_GAME_END_REASON_UNSPECIFIED GameEndReason = 0
	// All conditions are ok.
	GameEndReason_NORMAL GameEndReason = 1
	// One of players have less than zero points.
	GameEndReason_BANCROCITY GameEndReason = 2
	// Maximum possible wind played with non of player got required points to win.
	GameEndReason_MAX_WIND GameEndReason = 3
	// Dealer is first in orasu.
	GameEndReason_AGARI_YAME GameEndReason = 4
	// For some time-limited tournaments.
	GameEndReason_TIMEOUT GameEndReason = 5
)

var GameEndReason_name = map[int32]string{
	0: "GAME_END_REASON_UNSPECIFIED",
	1: "NORMAL",
	2: "BANCROCITY",
	3: "MAX_WIND",
	4: "AGARI_YAME",
	5: "TIMEOUT",
}

var GameEndReason_value = map[string]int32{
	"GAME_END_REASON_UNSPECIFIED": 0,
	"NORMAL":                      1,
	"BANCROCITY":                  2,
	"MAX_WIND":                    3,
	"AGARI_YAME":                  4,
	"TIMEOUT":                     5,
}

func (x GameEndReason) String() string {
	return proto.EnumName(GameEndReason_name, int32(x))
}

func (GameEndReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41e0d72543c57a28, []int{0}
}

type RoundEndReason int32

const (
	RoundEndReason_Round_END_REASON_UNSPECIFIED RoundEndReason = 0
	RoundEndReason_REASON_RON                   RoundEndReason = 1
	RoundEndReason_REASON_TSUMO                 RoundEndReason = 2
	// Game ended at last tile.
	RoundEndReason_REASON_REGULAR_DRAW RoundEndReason = 3
	// This is when game ended by special rule, ex. 4 riichi
	RoundEndReason_REASON_DRAW RoundEndReason = 4
)

var RoundEndReason_name = map[int32]string{
	0: "Round_END_REASON_UNSPECIFIED",
	1: "REASON_RON",
	2: "REASON_TSUMO",
	3: "REASON_REGULAR_DRAW",
	4: "REASON_DRAW",
}

var RoundEndReason_value = map[string]int32{
	"Round_END_REASON_UNSPECIFIED": 0,
	"REASON_RON":                   1,
	"REASON_TSUMO":                 2,
	"REASON_REGULAR_DRAW":          3,
	"REASON_DRAW":                  4,
}

func (x RoundEndReason) String() string {
	return proto.EnumName(RoundEndReason_name, int32(x))
}

func (RoundEndReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41e0d72543c57a28, []int{1}
}

type Log struct {
	Info   *GameInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Rounds []*Round  `protobuf:"bytes,2,rep,name=rounds,proto3" json:"rounds,omitempty"`
	// Uma+Oka changes.
	Changes              *Changes             `protobuf:"bytes,3,opt,name=changes,proto3" json:"changes,omitempty"`
	Started              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=started,proto3" json:"started,omitempty"`
	Ended                *timestamp.Timestamp `protobuf:"bytes,5,opt,name=ended,proto3" json:"ended,omitempty"`
	EndReason            GameEndReason        `protobuf:"varint,6,opt,name=end_reason,json=endReason,proto3,enum=log.GameEndReason" json:"end_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e0d72543c57a28, []int{0}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetInfo() *GameInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Log) GetRounds() []*Round {
	if m != nil {
		return m.Rounds
	}
	return nil
}

func (m *Log) GetChanges() *Changes {
	if m != nil {
		return m.Changes
	}
	return nil
}

func (m *Log) GetStarted() *timestamp.Timestamp {
	if m != nil {
		return m.Started
	}
	return nil
}

func (m *Log) GetEnded() *timestamp.Timestamp {
	if m != nil {
		return m.Ended
	}
	return nil
}

func (m *Log) GetEndReason() GameEndReason {
	if m != nil {
		return m.EndReason
	}
	return GameEndReason_GAME_END_REASON_UNSPECIFIED
}

type GameInfo struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Players              []*Player       `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Rules                *rules.Ruleset  `protobuf:"bytes,3,opt,name=rules,proto3" json:"rules,omitempty"`
	Timeouts             *rules.Timeouts `protobuf:"bytes,4,opt,name=timeouts,proto3" json:"timeouts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GameInfo) Reset()         { *m = GameInfo{} }
func (m *GameInfo) String() string { return proto.CompactTextString(m) }
func (*GameInfo) ProtoMessage()    {}
func (*GameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e0d72543c57a28, []int{1}
}

func (m *GameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameInfo.Unmarshal(m, b)
}
func (m *GameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameInfo.Marshal(b, m, deterministic)
}
func (m *GameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameInfo.Merge(m, src)
}
func (m *GameInfo) XXX_Size() int {
	return xxx_messageInfo_GameInfo.Size(m)
}
func (m *GameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GameInfo proto.InternalMessageInfo

func (m *GameInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GameInfo) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameInfo) GetRules() *rules.Ruleset {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *GameInfo) GetTimeouts() *rules.Timeouts {
	if m != nil {
		return m.Timeouts
	}
	return nil
}

// Represents starting tile positions.
type Wall struct {
	Wall    *base.Instances `protobuf:"bytes,1,opt,name=wall,proto3" json:"wall,omitempty"`
	Dora    *base.Instances `protobuf:"bytes,2,opt,name=dora,proto3" json:"dora,omitempty"`
	Ura     *base.Instances `protobuf:"bytes,3,opt,name=ura,proto3" json:"ura,omitempty"`
	Rinshan *base.Instances `protobuf:"bytes,4,opt,name=rinshan,proto3" json:"rinshan,omitempty"`
	// Hands for 4 players;
	Hands []*base.Instances `protobuf:"bytes,5,rep,name=hands,proto3" json:"hands,omitempty"`
	// To detect ex. seed.
	WallId string `protobuf:"bytes,6,opt,name=wall_id,json=wallId,proto3" json:"wall_id,omitempty"`
	// 2 numbers 1-6, representing dices.
	// Used only for UI representations.
	// Have no impact on a game.
	// Could be empty.
	Dice                 []int64  `protobuf:"varint,7,rep,packed,name=dice,proto3" json:"dice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wall) Reset()         { *m = Wall{} }
func (m *Wall) String() string { return proto.CompactTextString(m) }
func (*Wall) ProtoMessage()    {}
func (*Wall) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e0d72543c57a28, []int{2}
}

func (m *Wall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wall.Unmarshal(m, b)
}
func (m *Wall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wall.Marshal(b, m, deterministic)
}
func (m *Wall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wall.Merge(m, src)
}
func (m *Wall) XXX_Size() int {
	return xxx_messageInfo_Wall.Size(m)
}
func (m *Wall) XXX_DiscardUnknown() {
	xxx_messageInfo_Wall.DiscardUnknown(m)
}

var xxx_messageInfo_Wall proto.InternalMessageInfo

func (m *Wall) GetWall() *base.Instances {
	if m != nil {
		return m.Wall
	}
	return nil
}

func (m *Wall) GetDora() *base.Instances {
	if m != nil {
		return m.Dora
	}
	return nil
}

func (m *Wall) GetUra() *base.Instances {
	if m != nil {
		return m.Ura
	}
	return nil
}

func (m *Wall) GetRinshan() *base.Instances {
	if m != nil {
		return m.Rinshan
	}
	return nil
}

func (m *Wall) GetHands() []*base.Instances {
	if m != nil {
		return m.Hands
	}
	return nil
}

func (m *Wall) GetWallId() string {
	if m != nil {
		return m.WallId
	}
	return ""
}

func (m *Wall) GetDice() []int64 {
	if m != nil {
		return m.Dice
	}
	return nil
}

type Round struct {
	Info                 *RoundInfo   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Events               []*Event     `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	Result               *RoundResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Round) Reset()         { *m = Round{} }
func (m *Round) String() string { return proto.CompactTextString(m) }
func (*Round) ProtoMessage()    {}
func (*Round) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e0d72543c57a28, []int{3}
}

func (m *Round) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Round.Unmarshal(m, b)
}
func (m *Round) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Round.Marshal(b, m, deterministic)
}
func (m *Round) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Round.Merge(m, src)
}
func (m *Round) XXX_Size() int {
	return xxx_messageInfo_Round.Size(m)
}
func (m *Round) XXX_DiscardUnknown() {
	xxx_messageInfo_Round.DiscardUnknown(m)
}

var xxx_messageInfo_Round proto.InternalMessageInfo

func (m *Round) GetInfo() *RoundInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Round) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Round) GetResult() *RoundResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type RoundResult struct {
	// Resulting changes, calculated from money at the start of the round to the end of all payments done
	Changes *Changes `protobuf:"bytes,1,opt,name=changes,proto3" json:"changes,omitempty"`
	// Riichi sticks on the table at the end of the round and afer all payments
	RiichiCount          int64          `protobuf:"varint,2,opt,name=riichi_count,json=riichiCount,proto3" json:"riichi_count,omitempty"`
	EndReason            RoundEndReason `protobuf:"varint,3,opt,name=end_reason,json=endReason,proto3,enum=log.RoundEndReason" json:"end_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoundResult) Reset()         { *m = RoundResult{} }
func (m *RoundResult) String() string { return proto.CompactTextString(m) }
func (*RoundResult) ProtoMessage()    {}
func (*RoundResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e0d72543c57a28, []int{4}
}

func (m *RoundResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundResult.Unmarshal(m, b)
}
func (m *RoundResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundResult.Marshal(b, m, deterministic)
}
func (m *RoundResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundResult.Merge(m, src)
}
func (m *RoundResult) XXX_Size() int {
	return xxx_messageInfo_RoundResult.Size(m)
}
func (m *RoundResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundResult.DiscardUnknown(m)
}

var xxx_messageInfo_RoundResult proto.InternalMessageInfo

func (m *RoundResult) GetChanges() *Changes {
	if m != nil {
		return m.Changes
	}
	return nil
}

func (m *RoundResult) GetRiichiCount() int64 {
	if m != nil {
		return m.RiichiCount
	}
	return 0
}

func (m *RoundResult) GetEndReason() RoundEndReason {
	if m != nil {
		return m.EndReason
	}
	return RoundEndReason_Round_END_REASON_UNSPECIFIED
}

type RoundInfo struct {
	// 1-4 East, 5-8 South, 9-12 West, 13-16 North
	// Dealer calculated according to this number.
	RoundNumber int64 `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	// Number of riichi sticks at the moment of round starts.
	RiichiCount  int64 `protobuf:"varint,2,opt,name=riichi_count,json=riichiCount,proto3" json:"riichi_count,omitempty"`
	RenchanCount int64 `protobuf:"varint,3,opt,name=renchan_count,json=renchanCount,proto3" json:"renchan_count,omitempty"`
	// Player point at the moment of round starts.
	Money                []int64  `protobuf:"zigzag64,4,rep,packed,name=money,proto3" json:"money,omitempty"`
	Wall                 *Wall    `protobuf:"bytes,5,opt,name=wall,proto3" json:"wall,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoundInfo) Reset()         { *m = RoundInfo{} }
func (m *RoundInfo) String() string { return proto.CompactTextString(m) }
func (*RoundInfo) ProtoMessage()    {}
func (*RoundInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e0d72543c57a28, []int{5}
}

func (m *RoundInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundInfo.Unmarshal(m, b)
}
func (m *RoundInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundInfo.Marshal(b, m, deterministic)
}
func (m *RoundInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundInfo.Merge(m, src)
}
func (m *RoundInfo) XXX_Size() int {
	return xxx_messageInfo_RoundInfo.Size(m)
}
func (m *RoundInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoundInfo proto.InternalMessageInfo

func (m *RoundInfo) GetRoundNumber() int64 {
	if m != nil {
		return m.RoundNumber
	}
	return 0
}

func (m *RoundInfo) GetRiichiCount() int64 {
	if m != nil {
		return m.RiichiCount
	}
	return 0
}

func (m *RoundInfo) GetRenchanCount() int64 {
	if m != nil {
		return m.RenchanCount
	}
	return 0
}

func (m *RoundInfo) GetMoney() []int64 {
	if m != nil {
		return m.Money
	}
	return nil
}

func (m *RoundInfo) GetWall() *Wall {
	if m != nil {
		return m.Wall
	}
	return nil
}

type Player struct {
	// Player name, visible at the client.
	Caption              string   `protobuf:"bytes,1,opt,name=caption,proto3" json:"caption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e0d72543c57a28, []int{6}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func init() {
	proto.RegisterEnum("log.GameEndReason", GameEndReason_name, GameEndReason_value)
	proto.RegisterEnum("log.RoundEndReason", RoundEndReason_name, RoundEndReason_value)
	proto.RegisterType((*Log)(nil), "log.Log")
	proto.RegisterType((*GameInfo)(nil), "log.GameInfo")
	proto.RegisterType((*Wall)(nil), "log.Wall")
	proto.RegisterType((*Round)(nil), "log.Round")
	proto.RegisterType((*RoundResult)(nil), "log.RoundResult")
	proto.RegisterType((*RoundInfo)(nil), "log.RoundInfo")
	proto.RegisterType((*Player)(nil), "log.Player")
}

func init() { proto.RegisterFile("log/log.proto", fileDescriptor_41e0d72543c57a28) }

var fileDescriptor_41e0d72543c57a28 = []byte{
	// 816 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdd, 0x8e, 0xdb, 0x44,
	0x1b, 0xfe, 0x1c, 0xe7, 0x67, 0xf3, 0x26, 0x9b, 0xf5, 0xf7, 0x16, 0xa9, 0xd6, 0x02, 0x6a, 0xd6,
	0xa5, 0x28, 0x14, 0x35, 0x86, 0x85, 0x1b, 0x70, 0xb3, 0x66, 0x65, 0x69, 0x93, 0x54, 0xb3, 0x59,
	0x2d, 0xe5, 0xc4, 0x9a, 0xc4, 0x13, 0xc7, 0x60, 0xcf, 0x44, 0xfe, 0x69, 0xb5, 0x27, 0x5c, 0x01,
	0x12, 0x27, 0xdc, 0x05, 0x77, 0xc7, 0x15, 0xa0, 0x19, 0x8f, 0xb7, 0x1b, 0x4a, 0x81, 0x93, 0xd1,
	0xbc, 0xcf, 0xf3, 0x64, 0xe6, 0xfd, 0x79, 0x26, 0x86, 0xe3, 0x54, 0xc4, 0x6e, 0x2a, 0xe2, 0xe9,
	0x3e, 0x17, 0xa5, 0x40, 0x33, 0x15, 0xf1, 0xe9, 0x93, 0x58, 0x88, 0x38, 0x65, 0xae, 0x82, 0xd6,
	0xd5, 0xd6, 0x2d, 0x93, 0x8c, 0x15, 0x25, 0xcd, 0xf6, 0xb5, 0xea, 0xf4, 0x64, 0x4d, 0x0b, 0xe6,
	0xca, 0x45, 0x03, 0xff, 0xcf, 0xab, 0x94, 0x15, 0xae, 0x5a, 0x35, 0x64, 0xc9, 0x83, 0xd9, 0x1b,
	0xc6, 0xcb, 0x03, 0x64, 0x23, 0xb2, 0x4c, 0xf0, 0x1a, 0x71, 0x7e, 0x6d, 0x81, 0x79, 0x25, 0x62,
	0x3c, 0x83, 0x76, 0xc2, 0xb7, 0xc2, 0x36, 0xc6, 0xc6, 0x64, 0x70, 0x7e, 0x3c, 0x95, 0xf9, 0x5c,
	0xd2, 0x8c, 0x05, 0x7c, 0x2b, 0x88, 0xa2, 0xd0, 0x81, 0x6e, 0x2e, 0x2a, 0x1e, 0x15, 0x76, 0x6b,
	0x6c, 0x4e, 0x06, 0xe7, 0xa0, 0x44, 0x44, 0x42, 0x44, 0x33, 0xf8, 0x39, 0xf4, 0x36, 0x3b, 0xca,
	0x63, 0x56, 0xd8, 0xa6, 0x3a, 0x69, 0xa8, 0x44, 0xb3, 0x1a, 0x23, 0x0d, 0x89, 0xdf, 0x42, 0xaf,
	0x28, 0x69, 0x5e, 0xb2, 0xc8, 0x6e, 0x2b, 0xdd, 0xe9, 0xb4, 0xae, 0x78, 0xda, 0x54, 0x3c, 0x5d,
	0x35, 0x15, 0x93, 0x46, 0x8a, 0x5f, 0x41, 0x87, 0xf1, 0x88, 0x45, 0x76, 0xe7, 0x5f, 0x7f, 0x53,
	0x0b, 0xf1, 0x6b, 0x00, 0xc6, 0xa3, 0x30, 0x67, 0xb4, 0x10, 0xdc, 0xee, 0x8e, 0x8d, 0xc9, 0xe8,
	0x1c, 0xef, 0x8b, 0xf3, 0x79, 0x44, 0x14, 0x43, 0xfa, 0xac, 0xd9, 0x3a, 0xbf, 0x19, 0x70, 0xd4,
	0x54, 0x8e, 0x23, 0x68, 0x25, 0x91, 0x6a, 0x4a, 0x9f, 0xb4, 0x92, 0x08, 0x9f, 0x41, 0x6f, 0x9f,
	0xd2, 0x3b, 0x96, 0x37, 0x4d, 0x18, 0xa8, 0xc3, 0x5e, 0x29, 0x8c, 0x34, 0x1c, 0x7e, 0x06, 0x1d,
	0x35, 0x08, 0xdd, 0x84, 0xd1, 0xb4, 0x1e, 0x0b, 0x91, 0x2b, 0x2b, 0x49, 0x4d, 0xe2, 0x97, 0x70,
	0x24, 0xc7, 0x2a, 0xaa, 0xb2, 0xd0, 0x5d, 0x38, 0xd1, 0xc2, 0x95, 0x86, 0xc9, 0xbd, 0xc0, 0xf9,
	0xc3, 0x80, 0xf6, 0x2d, 0x4d, 0x53, 0x7c, 0x0a, 0xed, 0xb7, 0x34, 0x4d, 0xf5, 0xa4, 0x4e, 0xa6,
	0xca, 0x03, 0x01, 0x2f, 0x4a, 0xca, 0x37, 0xac, 0x20, 0x8a, 0x94, 0xa2, 0x48, 0xe4, 0xd4, 0x6e,
	0x7d, 0x40, 0x24, 0x49, 0x3c, 0x03, 0xb3, 0xca, 0xa9, 0xce, 0xf1, 0x3d, 0x8d, 0xe4, 0xf0, 0x0b,
	0xe8, 0xe5, 0x09, 0x2f, 0x76, 0x94, 0xdf, 0x67, 0xf8, 0x17, 0x59, 0xc3, 0xe3, 0x33, 0xe8, 0xec,
	0xa8, 0x74, 0x47, 0x47, 0x35, 0xe6, 0x3d, 0x61, 0xcd, 0xe2, 0x63, 0xe8, 0xc9, 0x0c, 0xc3, 0x24,
	0x52, 0xe3, 0xe8, 0x93, 0xae, 0x0c, 0x83, 0x08, 0x11, 0xda, 0x51, 0xb2, 0x61, 0x76, 0x6f, 0x6c,
	0x4e, 0x4c, 0xa2, 0xf6, 0xce, 0x1d, 0x74, 0x94, 0xbf, 0xd0, 0x39, 0xb0, 0xe7, 0xe8, 0x9d, 0xf3,
	0x0e, 0xfd, 0x59, 0x9b, 0xfd, 0xc0, 0x9f, 0xbe, 0x84, 0x88, 0x66, 0x70, 0x02, 0xdd, 0x9c, 0x15,
	0x55, 0x5a, 0xea, 0xaa, 0xad, 0x07, 0x1e, 0x56, 0x38, 0xd1, 0xbc, 0xf3, 0x8b, 0x01, 0x83, 0x07,
	0xf8, 0x43, 0x67, 0x1b, 0xff, 0xe4, 0xec, 0x33, 0x18, 0xe6, 0x49, 0xb2, 0xd9, 0x25, 0xe1, 0x46,
	0x54, 0xbc, 0x54, 0x13, 0x30, 0xc9, 0xa0, 0xc6, 0x66, 0x12, 0xc2, 0xf3, 0x03, 0x53, 0x9a, 0xca,
	0x94, 0x8f, 0xde, 0x25, 0xf2, 0xb7, 0xae, 0xfc, 0xdd, 0x80, 0xfe, 0x7d, 0xc1, 0xea, 0x12, 0x19,
	0x84, 0xbc, 0xca, 0xd6, 0x2c, 0x57, 0x19, 0xc9, 0x4b, 0x24, 0xb6, 0x50, 0xd0, 0x7f, 0xc9, 0xe3,
	0x29, 0x1c, 0xe7, 0x8c, 0xcb, 0xc4, 0xb5, 0xc6, 0x54, 0x9a, 0xa1, 0x06, 0x6b, 0xd1, 0x47, 0xd0,
	0xc9, 0x04, 0x67, 0x77, 0x76, 0x7b, 0x6c, 0x4e, 0x90, 0xd4, 0x01, 0x7e, 0xaa, 0x4d, 0x58, 0x3f,
	0xc4, 0xbe, 0x4a, 0x5e, 0xba, 0xb3, 0xb6, 0x9f, 0xe3, 0x40, 0xb7, 0x7e, 0x12, 0x68, 0x43, 0x6f,
	0x43, 0xf7, 0x65, 0x22, 0xb8, 0x7e, 0x45, 0x4d, 0xf8, 0xfc, 0x2d, 0x1c, 0x1f, 0xbc, 0x41, 0x7c,
	0x02, 0x1f, 0x5f, 0x7a, 0x73, 0x3f, 0xf4, 0x17, 0x17, 0x21, 0xf1, 0xbd, 0xeb, 0xe5, 0x22, 0xbc,
	0x59, 0x5c, 0xbf, 0xf2, 0x67, 0xc1, 0x77, 0x81, 0x7f, 0x61, 0xfd, 0x0f, 0x01, 0xba, 0x8b, 0x25,
	0x99, 0x7b, 0x57, 0x96, 0x81, 0x23, 0x80, 0x97, 0xde, 0x62, 0x46, 0x96, 0xb3, 0x60, 0xf5, 0xda,
	0x6a, 0xe1, 0x10, 0x8e, 0xe6, 0xde, 0xf7, 0xe1, 0x6d, 0xb0, 0xb8, 0xb0, 0x4c, 0xc9, 0x7a, 0x97,
	0x1e, 0x09, 0xc2, 0xd7, 0xde, 0xdc, 0xb7, 0xda, 0x38, 0x80, 0xde, 0x2a, 0x98, 0xfb, 0xcb, 0x9b,
	0x95, 0xd5, 0x79, 0xfe, 0x33, 0x8c, 0x0e, 0xfb, 0x8c, 0x63, 0xf8, 0x44, 0x21, 0x1f, 0xbe, 0x7a,
	0x04, 0xa0, 0x71, 0xb2, 0x5c, 0x58, 0x06, 0x5a, 0x30, 0xd4, 0xf1, 0xea, 0xfa, 0x66, 0xbe, 0xb4,
	0x5a, 0xf8, 0x18, 0x1e, 0x35, 0x0a, 0xff, 0xf2, 0xe6, 0xca, 0x23, 0xe1, 0x05, 0xf1, 0x6e, 0x2d,
	0x13, 0x4f, 0x60, 0xa0, 0x09, 0x05, 0xb4, 0x5f, 0xba, 0x3f, 0xbc, 0x88, 0x93, 0x72, 0x57, 0xad,
	0xa7, 0x1b, 0x91, 0xb9, 0x11, 0x17, 0x6f, 0x92, 0x9f, 0xc4, 0x76, 0xeb, 0x66, 0x74, 0xf7, 0xa3,
	0xe0, 0xf1, 0x0b, 0xba, 0x4f, 0xdc, 0x98, 0x71, 0xf5, 0xa7, 0x26, 0xbf, 0x0b, 0xeb, 0xae, 0xda,
	0x7e, 0xf3, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xc9, 0x95, 0xe0, 0x29, 0x06, 0x00, 0x00,
}
