FROM golang:1.11 as builder

ADD . /go/src/github.com/dnovikoff/mahjong-api
WORKDIR /go/src/github.com/dnovikoff/mahjong-api

RUN CGO_ENABLED=0 make gobin/log-server

FROM scratch
COPY --from=builder /go/src/github.com/dnovikoff/mahjong-api/gobin/log-server /usr/bin/log-server
VOLUME /logdb
CMD ["/usr/bin/log-server", "--config=/config.yaml"]
