FROM golang:1.19.6 as builder

ADD . /build
WORKDIR /build

RUN CGO_ENABLED=0 GOPROXY=off make gobin/log-server

FROM scratch
COPY --from=builder /build/gobin/log-server /usr/bin/log-server
VOLUME /logdb
CMD ["/usr/bin/log-server", "--config=/config.yaml"]
