// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: public/game/client.proto

package game

import (
	base "github.com/dnovikoff/mahjong-api/genproto/public/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Server will treat any incorrect answer as a cancel event.
// For example, when you try to Drop tile with riichi flag, on a wrong tile
// or when not in tempai - it will lead to tsumogiri.
// When you get Server response with, previously sent suggest_id and cancel=true,
// this means that the event is outdated (ex. priority action by other player or timeout).
// It is still safe to send answers on outdated event, in this case server
// just omits the answer and continues waiting for answer with valid suggest_id (if any).
type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// See Server.suggest.suggest_id
	SuggestId int64 `protobuf:"varint,1,opt,name=suggest_id,json=suggestId,proto3" json:"suggest_id,omitempty"`
	// Types that are assignable to OneofClient:
	//
	//	*Client_Cancel
	//	*Client_Drop
	//	*Client_Call
	//	*Client_Win
	//	*Client_Draw
	//	*Client_Noten
	//	*Client_ContinueGame
	//	*Client_Settings
	OneofClient isClient_OneofClient `protobuf_oneof:"oneof_client"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_game_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_public_game_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_public_game_client_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetSuggestId() int64 {
	if x != nil {
		return x.SuggestId
	}
	return 0
}

func (m *Client) GetOneofClient() isClient_OneofClient {
	if m != nil {
		return m.OneofClient
	}
	return nil
}

func (x *Client) GetCancel() bool {
	if x, ok := x.GetOneofClient().(*Client_Cancel); ok {
		return x.Cancel
	}
	return false
}

func (x *Client) GetDrop() *ClientDrop {
	if x, ok := x.GetOneofClient().(*Client_Drop); ok {
		return x.Drop
	}
	return nil
}

func (x *Client) GetCall() *base.Instances {
	if x, ok := x.GetOneofClient().(*Client_Call); ok {
		return x.Call
	}
	return nil
}

func (x *Client) GetWin() bool {
	if x, ok := x.GetOneofClient().(*Client_Win); ok {
		return x.Win
	}
	return false
}

func (x *Client) GetDraw() bool {
	if x, ok := x.GetOneofClient().(*Client_Draw); ok {
		return x.Draw
	}
	return false
}

func (x *Client) GetNoten() bool {
	if x, ok := x.GetOneofClient().(*Client_Noten); ok {
		return x.Noten
	}
	return false
}

func (x *Client) GetContinueGame() bool {
	if x, ok := x.GetOneofClient().(*Client_ContinueGame); ok {
		return x.ContinueGame
	}
	return false
}

func (x *Client) GetSettings() *Settings {
	if x, ok := x.GetOneofClient().(*Client_Settings); ok {
		return x.Settings
	}
	return nil
}

type isClient_OneofClient interface {
	isClient_OneofClient()
}

type Client_Cancel struct {
	// It is safe to answer cancel on any suggest.
	// In this case server will take default action.
	// For take is will be tsumogiri.
	// For call actions it will be any possible tile dropped.
	Cancel bool `protobuf:"varint,2,opt,name=cancel,proto3,oneof"`
}

type Client_Drop struct {
	Drop *ClientDrop `protobuf:"bytes,3,opt,name=drop,proto3,oneof"`
}

type Client_Call struct {
	// Selected tiles.
	// Server will autodetect call type.
	Call *base.Instances `protobuf:"bytes,4,opt,name=call,proto3,oneof"`
}

type Client_Win struct {
	Win bool `protobuf:"varint,5,opt,name=win,proto3,oneof"`
}

type Client_Draw struct {
	Draw bool `protobuf:"varint,6,opt,name=draw,proto3,oneof"`
}

type Client_Noten struct {
	Noten bool `protobuf:"varint,7,opt,name=noten,proto3,oneof"`
}

type Client_ContinueGame struct {
	ContinueGame bool `protobuf:"varint,8,opt,name=continue_game,json=continueGame,proto3,oneof"`
}

type Client_Settings struct {
	// New client settings, applied on server.
	Settings *Settings `protobuf:"bytes,9,opt,name=settings,proto3,oneof"`
}

func (*Client_Cancel) isClient_OneofClient() {}

func (*Client_Drop) isClient_OneofClient() {}

func (*Client_Call) isClient_OneofClient() {}

func (*Client_Win) isClient_OneofClient() {}

func (*Client_Draw) isClient_OneofClient() {}

func (*Client_Noten) isClient_OneofClient() {}

func (*Client_ContinueGame) isClient_OneofClient() {}

func (*Client_Settings) isClient_OneofClient() {}

type ClientDrop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instance int64 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Riichi   bool  `protobuf:"varint,2,opt,name=riichi,proto3" json:"riichi,omitempty"`
}

func (x *ClientDrop) Reset() {
	*x = ClientDrop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_game_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDrop) ProtoMessage() {}

func (x *ClientDrop) ProtoReflect() protoreflect.Message {
	mi := &file_public_game_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDrop.ProtoReflect.Descriptor instead.
func (*ClientDrop) Descriptor() ([]byte, []int) {
	return file_public_game_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientDrop) GetInstance() int64 {
	if x != nil {
		return x.Instance
	}
	return 0
}

func (x *ClientDrop) GetRiichi() bool {
	if x != nil {
		return x.Riichi
	}
	return false
}

// Settings will be applied on server, even when disconnected.
// You will get confirmation on settings changes from server (see Server.settings).
type Settings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DropTsumo  bool `protobuf:"varint,1,opt,name=drop_tsumo,json=dropTsumo,proto3" json:"drop_tsumo,omitempty"`
	AutoWin    bool `protobuf:"varint,2,opt,name=auto_win,json=autoWin,proto3" json:"auto_win,omitempty"`
	NoDeclare  bool `protobuf:"varint,3,opt,name=no_declare,json=noDeclare,proto3" json:"no_declare,omitempty"`
	AutoTempai bool `protobuf:"varint,4,opt,name=auto_tempai,json=autoTempai,proto3" json:"auto_tempai,omitempty"`
	// For optional agari-yame
	AutoEndGame bool `protobuf:"varint,5,opt,name=auto_end_game,json=autoEndGame,proto3" json:"auto_end_game,omitempty"`
}

func (x *Settings) Reset() {
	*x = Settings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_game_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_public_game_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_public_game_client_proto_rawDescGZIP(), []int{2}
}

func (x *Settings) GetDropTsumo() bool {
	if x != nil {
		return x.DropTsumo
	}
	return false
}

func (x *Settings) GetAutoWin() bool {
	if x != nil {
		return x.AutoWin
	}
	return false
}

func (x *Settings) GetNoDeclare() bool {
	if x != nil {
		return x.NoDeclare
	}
	return false
}

func (x *Settings) GetAutoTempai() bool {
	if x != nil {
		return x.AutoTempai
	}
	return false
}

func (x *Settings) GetAutoEndGame() bool {
	if x != nil {
		return x.AutoEndGame
	}
	return false
}

var File_public_game_client_proto protoreflect.FileDescriptor

var file_public_game_client_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x61, 0x68, 0x6a,
	0x6f, 0x6e, 0x67, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x1a, 0x16, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xcf, 0x02, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x63, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x63, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x72, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x72, 0x6f, 0x70, 0x48, 0x00, 0x52, 0x04,
	0x64, 0x72, 0x6f, 0x70, 0x12, 0x2d, 0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x48, 0x00, 0x52, 0x04, 0x63,
	0x61, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x72, 0x61, 0x77, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x64, 0x72, 0x61, 0x77, 0x12, 0x16, 0x0a,
	0x05, 0x6e, 0x6f, 0x74, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05,
	0x6e, 0x6f, 0x74, 0x65, 0x6e, 0x12, 0x25, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75,
	0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x08,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x42, 0x0e, 0x0a, 0x0c, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x5f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x22, 0x40, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x72, 0x6f, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x69, 0x69, 0x63, 0x68, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x69,
	0x69, 0x63, 0x68, 0x69, 0x22, 0xa8, 0x01, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x72, 0x6f, 0x70, 0x5f, 0x74, 0x73, 0x75, 0x6d, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x72, 0x6f, 0x70, 0x54, 0x73, 0x75, 0x6d, 0x6f,
	0x12, 0x19, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x61, 0x75, 0x74, 0x6f, 0x57, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6e,
	0x6f, 0x5f, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x6e, 0x6f, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x75,
	0x74, 0x6f, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x61, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x61, 0x75, 0x74, 0x6f, 0x54, 0x65, 0x6d, 0x70, 0x61, 0x69, 0x12, 0x22, 0x0a, 0x0d, 0x61,
	0x75, 0x74, 0x6f, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x6f, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x42,
	0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6e,
	0x6f, 0x76, 0x69, 0x6b, 0x6f, 0x66, 0x66, 0x2f, 0x6d, 0x61, 0x68, 0x6a, 0x6f, 0x6e, 0x67, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_public_game_client_proto_rawDescOnce sync.Once
	file_public_game_client_proto_rawDescData = file_public_game_client_proto_rawDesc
)

func file_public_game_client_proto_rawDescGZIP() []byte {
	file_public_game_client_proto_rawDescOnce.Do(func() {
		file_public_game_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_public_game_client_proto_rawDescData)
	})
	return file_public_game_client_proto_rawDescData
}

var file_public_game_client_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_public_game_client_proto_goTypes = []interface{}{
	(*Client)(nil),         // 0: mahjong.game.Client
	(*ClientDrop)(nil),     // 1: mahjong.game.ClientDrop
	(*Settings)(nil),       // 2: mahjong.game.Settings
	(*base.Instances)(nil), // 3: mahjong.base.Instances
}
var file_public_game_client_proto_depIdxs = []int32{
	1, // 0: mahjong.game.Client.drop:type_name -> mahjong.game.ClientDrop
	3, // 1: mahjong.game.Client.call:type_name -> mahjong.base.Instances
	2, // 2: mahjong.game.Client.settings:type_name -> mahjong.game.Settings
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_public_game_client_proto_init() }
func file_public_game_client_proto_init() {
	if File_public_game_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_public_game_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_game_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDrop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_game_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Settings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_public_game_client_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Client_Cancel)(nil),
		(*Client_Drop)(nil),
		(*Client_Call)(nil),
		(*Client_Win)(nil),
		(*Client_Draw)(nil),
		(*Client_Noten)(nil),
		(*Client_ContinueGame)(nil),
		(*Client_Settings)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_public_game_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_game_client_proto_goTypes,
		DependencyIndexes: file_public_game_client_proto_depIdxs,
		MessageInfos:      file_public_game_client_proto_msgTypes,
	}.Build()
	File_public_game_client_proto = out.File
	file_public_game_client_proto_rawDesc = nil
	file_public_game_client_proto_goTypes = nil
	file_public_game_client_proto_depIdxs = nil
}
