// Code generated by protoc-gen-go. DO NOT EDIT.
// source: public/base/base.proto

package base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Wind int32

const (
	Wind_WIND_UNSPECIFIED Wind = 0
	Wind_EAST             Wind = 1
	Wind_SOUTH            Wind = 2
	Wind_WEST             Wind = 3
	Wind_NORTH            Wind = 4
)

var Wind_name = map[int32]string{
	0: "WIND_UNSPECIFIED",
	1: "EAST",
	2: "SOUTH",
	3: "WEST",
	4: "NORTH",
}

var Wind_value = map[string]int32{
	"WIND_UNSPECIFIED": 0,
	"EAST":             1,
	"SOUTH":            2,
	"WEST":             3,
	"NORTH":            4,
}

func (x Wind) String() string {
	return proto.EnumName(Wind_name, int32(x))
}

func (Wind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_94647f61fd50d261, []int{0}
}

type Limit int32

const (
	Limit_LIMIT_UNSPECIFIED Limit = 0
	Limit_MANGAN            Limit = 1
	Limit_HANEMAN           Limit = 2
	Limit_BAIMAN            Limit = 3
	Limit_SANBAIMAN         Limit = 4
	Limit_YAKUMAN           Limit = 5
)

var Limit_name = map[int32]string{
	0: "LIMIT_UNSPECIFIED",
	1: "MANGAN",
	2: "HANEMAN",
	3: "BAIMAN",
	4: "SANBAIMAN",
	5: "YAKUMAN",
}

var Limit_value = map[string]int32{
	"LIMIT_UNSPECIFIED": 0,
	"MANGAN":            1,
	"HANEMAN":           2,
	"BAIMAN":            3,
	"SANBAIMAN":         4,
	"YAKUMAN":           5,
}

func (x Limit) String() string {
	return proto.EnumName(Limit_name, int32(x))
}

func (Limit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_94647f61fd50d261, []int{1}
}

type Opponent int32

const (
	Opponent_OPPONENT_UNSPECIFIED Opponent = 0
	Opponent_SELF                 Opponent = 1
	Opponent_RIGHT                Opponent = 2
	Opponent_FRONT                Opponent = 3
	Opponent_LEFT                 Opponent = 4
)

var Opponent_name = map[int32]string{
	0: "OPPONENT_UNSPECIFIED",
	1: "SELF",
	2: "RIGHT",
	3: "FRONT",
	4: "LEFT",
}

var Opponent_value = map[string]int32{
	"OPPONENT_UNSPECIFIED": 0,
	"SELF":                 1,
	"RIGHT":                2,
	"FRONT":                3,
	"LEFT":                 4,
}

func (x Opponent) String() string {
	return proto.EnumName(Opponent_name, int32(x))
}

func (Opponent) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_94647f61fd50d261, []int{2}
}

// Special holder to be used in repeat.
type Instances struct {
	Instances            []int64  `protobuf:"varint,1,rep,packed,name=instances,proto3" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instances) Reset()         { *m = Instances{} }
func (m *Instances) String() string { return proto.CompactTextString(m) }
func (*Instances) ProtoMessage()    {}
func (*Instances) Descriptor() ([]byte, []int) {
	return fileDescriptor_94647f61fd50d261, []int{0}
}

func (m *Instances) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instances.Unmarshal(m, b)
}
func (m *Instances) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instances.Marshal(b, m, deterministic)
}
func (m *Instances) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instances.Merge(m, src)
}
func (m *Instances) XXX_Size() int {
	return xxx_messageInfo_Instances.Size(m)
}
func (m *Instances) XXX_DiscardUnknown() {
	xxx_messageInfo_Instances.DiscardUnknown(m)
}

var xxx_messageInfo_Instances proto.InternalMessageInfo

func (m *Instances) GetInstances() []int64 {
	if m != nil {
		return m.Instances
	}
	return nil
}

type Meld struct {
	// Oponent is set, related to one who declared
	Opponent       Opponent `protobuf:"varint,1,opt,name=opponent,proto3,enum=mahjong.base.Opponent" json:"opponent,omitempty"`
	CalledInstance int64    `protobuf:"varint,2,opt,name=called_instance,json=calledInstance,proto3" json:"called_instance,omitempty"`
	// Only for upgraded pon
	UpgradeInstance int64      `protobuf:"varint,3,opt,name=upgrade_instance,json=upgradeInstance,proto3" json:"upgrade_instance,omitempty"`
	Hand            *Instances `protobuf:"bytes,4,opt,name=hand,proto3" json:"hand,omitempty"`
	// To identify melds on the table.
	// In case of pon upgrade the meld_id will correspond to upgraded pon.
	MeldId int64 `protobuf:"varint,5,opt,name=meld_id,json=meldId,proto3" json:"meld_id,omitempty"`
	// When closed kan declared (or upgrade)
	IncludesTsumo        bool     `protobuf:"varint,6,opt,name=includes_tsumo,json=includesTsumo,proto3" json:"includes_tsumo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meld) Reset()         { *m = Meld{} }
func (m *Meld) String() string { return proto.CompactTextString(m) }
func (*Meld) ProtoMessage()    {}
func (*Meld) Descriptor() ([]byte, []int) {
	return fileDescriptor_94647f61fd50d261, []int{1}
}

func (m *Meld) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meld.Unmarshal(m, b)
}
func (m *Meld) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meld.Marshal(b, m, deterministic)
}
func (m *Meld) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meld.Merge(m, src)
}
func (m *Meld) XXX_Size() int {
	return xxx_messageInfo_Meld.Size(m)
}
func (m *Meld) XXX_DiscardUnknown() {
	xxx_messageInfo_Meld.DiscardUnknown(m)
}

var xxx_messageInfo_Meld proto.InternalMessageInfo

func (m *Meld) GetOpponent() Opponent {
	if m != nil {
		return m.Opponent
	}
	return Opponent_OPPONENT_UNSPECIFIED
}

func (m *Meld) GetCalledInstance() int64 {
	if m != nil {
		return m.CalledInstance
	}
	return 0
}

func (m *Meld) GetUpgradeInstance() int64 {
	if m != nil {
		return m.UpgradeInstance
	}
	return 0
}

func (m *Meld) GetHand() *Instances {
	if m != nil {
		return m.Hand
	}
	return nil
}

func (m *Meld) GetMeldId() int64 {
	if m != nil {
		return m.MeldId
	}
	return 0
}

func (m *Meld) GetIncludesTsumo() bool {
	if m != nil {
		return m.IncludesTsumo
	}
	return false
}

func init() {
	proto.RegisterEnum("mahjong.base.Wind", Wind_name, Wind_value)
	proto.RegisterEnum("mahjong.base.Limit", Limit_name, Limit_value)
	proto.RegisterEnum("mahjong.base.Opponent", Opponent_name, Opponent_value)
	proto.RegisterType((*Instances)(nil), "mahjong.base.Instances")
	proto.RegisterType((*Meld)(nil), "mahjong.base.Meld")
}

func init() { proto.RegisterFile("public/base/base.proto", fileDescriptor_94647f61fd50d261) }

var fileDescriptor_94647f61fd50d261 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xd1, 0x6f, 0x93, 0x50,
	0x14, 0xc6, 0xa5, 0xd0, 0x8e, 0x9e, 0xb9, 0xed, 0x7a, 0x33, 0x37, 0x1e, 0x7c, 0x20, 0x4b, 0x8c,
	0xac, 0x46, 0x48, 0x6a, 0x8c, 0xcf, 0xcc, 0xc1, 0x4a, 0x6c, 0x2f, 0x0d, 0xd0, 0x34, 0xfa, 0x42,
	0x28, 0x97, 0xb5, 0x57, 0xe1, 0x42, 0x06, 0xf8, 0xcf, 0xfb, 0x62, 0x2e, 0x2b, 0xdd, 0xd4, 0x17,
	0x72, 0xbf, 0xdf, 0xf9, 0xf2, 0xe5, 0xe3, 0xe4, 0xc0, 0x45, 0xd5, 0x6e, 0x72, 0x96, 0x5a, 0x9b,
	0xa4, 0xce, 0xba, 0x8f, 0x59, 0x3d, 0x94, 0x4d, 0x89, 0x5f, 0x16, 0xc9, 0xee, 0x47, 0xc9, 0xb7,
	0xa6, 0x60, 0x57, 0xd7, 0x30, 0xf6, 0x78, 0xdd, 0x24, 0x3c, 0xcd, 0x6a, 0xfc, 0x06, 0xc6, 0xac,
	0x17, 0x9a, 0xa4, 0xcb, 0x86, 0x1c, 0x3c, 0x81, 0xab, 0xdf, 0x12, 0x28, 0x8b, 0x2c, 0xa7, 0x78,
	0x0a, 0x6a, 0x59, 0x55, 0x25, 0xcf, 0x78, 0xa3, 0x49, 0xba, 0x64, 0x9c, 0x4e, 0x2f, 0xcc, 0xe7,
	0xa1, 0xa6, 0xbf, 0x9f, 0x06, 0x07, 0x1f, 0x7e, 0x07, 0x67, 0x69, 0x92, 0xe7, 0x19, 0x8d, 0xfb,
	0x40, 0x6d, 0xa0, 0x4b, 0x86, 0x1c, 0x9c, 0x3e, 0xe2, 0xbe, 0x04, 0xbe, 0x06, 0xd4, 0x56, 0xdb,
	0x87, 0x84, 0x66, 0x4f, 0x4e, 0xb9, 0x73, 0x9e, 0xed, 0xf9, 0xc1, 0xfa, 0x1e, 0x94, 0x5d, 0xc2,
	0xa9, 0xa6, 0xe8, 0x92, 0x71, 0x3c, 0xbd, 0xfc, 0xbb, 0xc3, 0xe1, 0xaf, 0x82, 0xce, 0x84, 0x2f,
	0xe1, 0xa8, 0xc8, 0x72, 0x1a, 0x33, 0xaa, 0x0d, 0xbb, 0xb8, 0x91, 0x90, 0x1e, 0xc5, 0x6f, 0xe1,
	0x94, 0xf1, 0x34, 0x6f, 0x69, 0x56, 0xc7, 0x4d, 0xdd, 0x16, 0xa5, 0x36, 0xd2, 0x25, 0x43, 0x0d,
	0x4e, 0x7a, 0x1a, 0x09, 0x38, 0x71, 0x41, 0x59, 0x33, 0x4e, 0xf1, 0x39, 0xa0, 0xb5, 0x47, 0x6e,
	0xe3, 0x15, 0x09, 0x97, 0xce, 0x17, 0xcf, 0xf5, 0x9c, 0x5b, 0xf4, 0x02, 0xab, 0xa0, 0x38, 0x76,
	0x18, 0x21, 0x09, 0x8f, 0x61, 0x18, 0xfa, 0xab, 0x68, 0x86, 0x06, 0x02, 0xae, 0x9d, 0x30, 0x42,
	0xb2, 0x80, 0xc4, 0x0f, 0xa2, 0x19, 0x52, 0x26, 0x31, 0x0c, 0xe7, 0xac, 0x60, 0x0d, 0x7e, 0x0d,
	0xaf, 0xe6, 0xde, 0xc2, 0x8b, 0xfe, 0x49, 0x02, 0x18, 0x2d, 0x6c, 0x72, 0x67, 0x13, 0x24, 0xe1,
	0x63, 0x38, 0x9a, 0xd9, 0xc4, 0x59, 0xd8, 0x04, 0x0d, 0xc4, 0xe0, 0xc6, 0xf6, 0xc4, 0x5b, 0xc6,
	0x27, 0x30, 0x0e, 0x6d, 0xb2, 0x97, 0x8a, 0xf0, 0x7d, 0xb3, 0xbf, 0xae, 0x84, 0x18, 0x4e, 0x08,
	0xa8, 0xfd, 0xfe, 0xb1, 0x06, 0xe7, 0xfe, 0x72, 0xe9, 0x13, 0x87, 0x44, 0xff, 0x17, 0x0e, 0x9d,
	0xb9, 0xfb, 0x58, 0x38, 0xf0, 0xee, 0x66, 0x11, 0x1a, 0x88, 0xa7, 0x1b, 0xf8, 0x44, 0x34, 0x56,
	0x41, 0x99, 0x3b, 0x6e, 0x84, 0x94, 0x9b, 0xcf, 0xdf, 0x3f, 0x6d, 0x59, 0xb3, 0x6b, 0x37, 0x66,
	0x5a, 0x16, 0x16, 0xe5, 0xe5, 0x2f, 0xf6, 0xb3, 0xbc, 0xbf, 0xb7, 0xf6, 0xdb, 0xfe, 0x90, 0x54,
	0xcc, 0xda, 0x66, 0xbc, 0x3b, 0x2e, 0xeb, 0xd9, 0xcd, 0x6d, 0x46, 0x1d, 0xfa, 0xf8, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x57, 0xc8, 0xe1, 0xc3, 0x89, 0x02, 0x00, 0x00,
}
